[package]
name = "test_lexer"
version = "0.1.0"
authors = ["root"]

[[bin]]
doc = false
name = "test_lexer"

[build-dependencies]
lrlex = "0.5"
lrpar = "0.5"

[dependencies]
lrlex = "0.5"
lrpar = "0.5"